VKode/Users/urls.py
from django.urls import path
from . import views
from .views import CustomTokenObtainPairView, UserProfileView
from rest_framework_simplejwt.views import TokenRefreshView

app_name = "users"

urlpatterns = [
    path("api/token/", CustomTokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/profile/", UserProfileView.as_view(), name="user_profile"),
    path("login/", views.LoginUser.as_view(), name="login"),
    path("registration/", views.RegisterUser.as_view(), name="registration"),
    path("logout/", views.logout_user, name="logout"),
]

VKode/VKode/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("QR_generator.urls")),
    path("users/", include("Users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VKode/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <link type="text/css" href="{% static 'generator/css/styles.css' %}" rel="stylesheet" />
</head>
<body>
<header>
    <div class="container">
        <div class="logo">
            <a href="{% url 'index' %}">VKode</a>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'index' %}">Главная</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'dashboard' %}">QR Коды</a></li>
                <li><a href="{% url 'create_code' %}">Создать QR код</a></li>
                <li><a href="{% url 'users:logout' %}">Выйти</a></li>
                {% else %}
                <li><a href="{% url 'users:login' %}">Войти</a></li>
                <li><a href="{% url 'users:registration' %}">Зарегистрироваться</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>

<main>
    <div class="container">
        {% block content %} {% endblock content %}
    </div>
</main>

<footer>
    <div class="container">
        <p>&copy; 2024 VKode. All rights reserved.</p>
    </div>
</footer>
</body>
</html>